name: flutter_inapp_purchase
description: In App Purchase plugin for flutter. This project has been forked by
  react-native-iap and we are willing to share same experience with that on
  react-native.
version: 8.2.0
homepage: https://github.com/hyochan/flutter_inapp_purchase/blob/main/pubspec.yaml
environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  meta: ^1.11.0
  platform: ^3.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.4
  test: ^1.25.0

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: io.github.hyochan.flutter_inapp_purchase
        pluginClass: FlutterInappPurchasePlugin
      ios:
        pluginClass: FlutterInappPurchasePlugin
      macos:
        pluginClass: FlutterInappPurchasePlugin
